# =============================================================================================
# = DATA SOURCE
# =============================================================================================
spring:
  #  jpa:
  #    hibernate.ddl-auto: validate
  #    properties:
  #      hibernate:
  #        jdbc:
  #          lob:
  #            non_contextual_creation: true
  #        default_schema: hrm
  #  datasource:
  #    url: jdbc:postgresql://localhost:5432/grp
  #    username: grp
  #    password: grp
  application:
    name: hrm-service-pim-lo
    #    global_url: "http://grp.gov.bd/global/api/"
    global_url: "http://45.79.102.237:8011/"
    #    zuul_url: "http://45.79.102.237:8011/"
    zuul_url: "http://localhost:8001/"
    cmn_app_name: ""
    hrm_app_name: ""
    global: true
    search_from_global: false
    #    gdata_end_point_url: "http://43.224.110.22:80/hrm/"
    gdata_end_point_url: "http://localhost:5000/hrm/"
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  banner.location: classpath:banner.txt

#  zipkin:
#    base-url: http://45.79.102.237:9411/
#  sleuth:
#    sampler:
#      probability: 1


# =============================================================================================
# = SERVICE
# =============================================================================================
service:
  properties:
    short-code: hrm-service-pim
    version: v1.0
server:
  port : 9001


# =============================================================================================
# = EUREKA
# =============================================================================================
#eureka:
# instance:
#   prefer-ip-address: true
#   ipAddress: 45.33.38.145
#   appname: "${spring.application.name}"
#   leaseExpirationDurationInSeconds: 2
#   leaseRenewalIntervalInSeconds: 1
# client:
#   registerWithEureka: true
#   fetchRegistry: true
#   serviceUrl:
#     defaultZone: "${DISCOVERY_URL:http://45.79.102.237:8010}/eureka/"
eureka:
  client:
    enabled: false
